### ISSUE TITLE
when i make beef ,there have some error happen

### ISSUE THREAD

**Issue by tuzhih** [vossjo/libbeef#1]
make beef then  appear as follows
“
checking dependency style of icc... gcc3
./configure: line 3436: AX_COMPILER_VENDOR: command not found
./configure: line 3437: AX_CC_MAXOPT: command not found
./configure: line 3438: syntax error near unexpected token `-std=c99,'
./configure: line 3438: `AX_CHECK_COMPILE_FLAG(-std=c99, CFLAGS="$CFLAGS -std=c99")'
make: *** [config.status] Error
"
How to deal with it ?

**Comment by vossjo** [comment]
Committed [2822afe](https://github.com/vossjo/libbeef/commit/2822afe3da255a57b078779201f2fd6582b9a5e7) which should fix this.
Differences in autoconf versions (between configure usage and configure generation) triggered unnecessary autoreconf. autoreconf requires macros under GPL license that are not included here since libbeef is LGPL. The lack of these macros leads to the above compile flag checking errors.
With the fixed build process, running configure should work as expected (without these macros).
