### ISSUE TITLE
About ldmy issue when I add beef to the compilation of  vasp 6.3.2

### ISSUE THREAD

**Issue by chenyangchang** [vossjo/libbeef#4]
Hello
When I add beef to the compilation of vasp 6.3.2, it come out the issue: ld: cannot find -ldmy, could you help me and tell the reason? thank you.

**Comment by vossjo** [comment]
When the build process tries to link, giving the above error, does the printed link statement `mpif90 -o ... -ldmy ...` contain `-Llib` before `-ldmy`? If not, that's reason for the build failure.
libdmy.a is a VASP-internal library. So that it can be found when the VASP binaries are linked, there should be a `-Llib` (thus pointing the linker to the lib directory in the VASP tree) in the LLIB variable, and the VASP build system defines that internally. User-specific adjustments for compiling and linking are defined in _makefile.include_, and one must make sure to not overwrite the the LLIB variable, but append to it via `LLIB += youroptions`, rather than `LLIB = youroptions`.
