### ISSUE TITLE
Interpretation of BEEF-vdw result in Qunatum Espresso. 

### ISSUE THREAD

**Issue by jungsdao** [vossjo/libbeef#5]
Hello, I just started using BEEF-vdw functional in Quantum espresso. 
But I'm a bit confused when interpreting the output of BEEF-vdw result. 

`!    total energy              =   -1647.49506764 Ry
     estimated scf accuracy    <       0.00000029 Ry
     smearing contrib. (-TS)   =      -0.14223212 Ry
     internal energy E=F+TS    =   -1647.35283552 Ry

     The total energy is F=E-TS. E is the sum of the following terms:
     one-electron contribution =  -24487.16232287 Ry
     hartree contribution      =   12436.92699083 Ry
     xc contribution           =    -320.35071527 Ry
     ewald contribution        =   10723.23320899 Ry
     electric field correction =       0.00000279 Ry`

I wanted to see how Bayesian Error Estimation is distributed according to following output ::

``` 
BEEFens 2000 ensemble energies
             -0.234925644247402E+02
             -0.622047017039314E+00
             -0.497032197700053E+01
              0.141418418499206E+02
             -0.708132985011825E+01```

The error distribution can be plotted as following. 
But I think the error distribution is too wide if I assume the printed output is in "Ry" unit. 
I might have made some mistake during my calculation or I might be interpreting this in a wrong way. 
could you enlighten me how should I read the output?
Also Is there any easy way to read ensemble energy with ASE function? 
Many thanks in advance. 

![BEEF_error](https://user-images.githubusercontent.com/47560396/224289266-2735356a-726e-4734-aa40-ca64d0fede03.png)

**Comment by vossjo** [comment]
First of all, yes, these energies are in Rydberg in the case of QE (`libbeef` uses Hartree atomic energies internally, but when xc energies are printed, those are in units the DFT code uses at this point). The cost function used to optimize the BEEF functional(s) was entirely based on total energy differences, and strictly speaking only looking at the standard deviation of differences between different states of the system or products and reactants make sense for the corresponding Bayesian error analysis. So what one should do is take the 2000 ensemble energies for e.g. all products and subtract, energy by energy, the ensemble for the reactants. The standard deviation of these 2000 energy differences then yields an error estimate for the reaction energy.

I'm not sure which versions of ASE or other ASE-QE interfaces might have functionality to directly read in these ensemble energies, but this can be achieved with only a few lines of python:
```python
import numpy as np

def getensemble(output):
    out = open(output)
    lines = out.readlines()
    out.close()
    lastensemble = -1
    for i,l in enumerate(lines):
        if l.find('BEEFens 2000 ensemble energies')>-1:
            lastensemble = i
    if lastensemble==-1:
        raise RuntimeError('No BEEF ensemble found in '+output)
    ensemble = np.array([float(x) for x in lines[lastensemble+1:lastensemble+2001]])
    return ensemble

BEEF_err_H2_bind = np.std(getensemble('H2_output.log') - 2*getensemble('H_output.log'))
```
Here, `H2_output.log` would be QE's output for a BEEF calculation of the H<sub>2</sub> molecule, and `H_output.log` the corresponding output for the H atom. Subtracting the H ensemble energies twice from the H<sub>2</sub> ensemble energies (in analogy to the calculation of the binding energy from the corresponding total energy differences), and computing the standard deviation of these differences as shown above, yields an error estimate for the binding energy of H<sub>2</sub>. Alternatively, one can use the `bee` command line utility included with `libbeef` to compute these energy differences and standard deviations.

Secondly, yes, the spread of (total) xc ensemble energies for an individual system is typically huge! The corresponding ensemble of xc functionals is very broad for the BEEF vdW type functionals, see e.g. Figure 4 in the [meta-BEEF vdW paper](https://www.osti.gov/servlets/purl/1349403) (a different BEEF functional, but linking it here because there is a preprint of it), and this leads to a huge spread of ensemble exchange energies. When looking at exchange energy differences between different systems, most of that cancels. We are aware of how big this xc functional spread is and have developed new functionals, that are not purely data science-based, but that also fulfill important physical constraints: https://github.com/vossgroup/CML. For these constrained and machine-learned functionals, the ensemble spread is much smaller (see e.g. Figure 4 in the [MCML functional paper](https://www.osti.gov/biblio/1818520)). For the (analytical density of an) H atom, e.g., the MCML functional yields the exact exchange energy and predicts a zero error on this result. Stay tuned for code to compute error estimates with the [CML](https://github.com/vossgroup/CML) functionals in various DFT codes (as standard DFT exchange-correlation functionals, they already can be employed via [libxc](https://gitlab.com/libxc/libxc), and yield both good surface chemical and bulk structural properties.)
